[package]
name = "minimark"
description = "a tiny, easy to use markdown compiler."
authors = [ "Legoraft <legoraft@skiff.com>" ]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
